name: Backport
on:
  pull_request_target:
    types: [closed, labeled]

jobs:
  backport:
    name: Backport Action
    if: |
      github.event.pull_request.merged == true
      && contains(github.event.pull_request.labels.*.name, 'auto-backport')
      && (
        (github.event.action == 'labeled' && github.event.label.name == 'auto-backport')
        || (github.event.action == 'closed')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Backport
        uses: sqren/backport-github-action@v1
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          target_pr_labels: 'backport'